Add SocketCAN functionality
unofficial-rev-port/CANBridge pull request #5
Opened 2024-08-21 22:08 UTC by garrettsummerfi3ld

Implemented the Linux [SocketCAN](https://docs.kernel.org/networking/can.html) driver into CANBridge.

This is based off of the [`REVrobotics/CANBridge`](https://github.com/REVrobotics/CANBridge) [SocketCAN](https://github.com/REVrobotics/CANBridge/tree/SocketCAN) branch with lots of updates to compiling, driver code, and rewriting SocketCAN related code already existing to utilize the Linux kernel drivers.

2024-08-22 01:01 UTC, ItsHarper requested changes
Reviewing this will probably take a while. Feel free to ping me if it's been a while since I've left any comments. It's good to see progress being made!

2024-08-22 01:01 UTC, ItsHarper commented on src/main/native/cpp/CANBridge.cpp
> +    new rev::usb::SerialDriver()
I'm not sure if this is Toth's old branch or a change you made, but please remove this line (as I've mentioned previously, I'd prefer to fully delete the old serial driver before we merge in cross-platform support)

2024-08-22 01:01 UTC, ItsHarper commented on src/main/native/cpp/Drivers/SocketCAN/SocketCANDevice.cpp
> +        m_name = "SPARK MAX";
We definitely don't want to hardcode this to "SPARK MAX". Ideally we'd get this information from the Linux kernel. I think the way to do this might be the `gs_usb_probe()` function (see what `usb_interface.dev.init_name` gives you).

If we can't figure that out and up needing to hardcode, use "USB CAN Device".

2024-08-22 01:15 UTC, NoahAndrews commented on src/main/native/cpp/Drivers/SocketCAN/SocketCANDevice.cpp
> +        m_name = "SPARK MAX";
That function may not be available to you. I momentarily forgot that we're using the SocketCAN system, not the gs_usb kernel driver directly.

2024-08-22 01:27 UTC, NoahAndrews commented on src/main/native/cpp/Drivers/SocketCAN/SocketCANDevice.cpp
> +        m_name = "SPARK MAX";
For now you can feel free to just hardcore it.

2024-08-22 14:48 UTC, garrettsummerfi3ld commented on src/main/native/cpp/CANBridge.cpp
> +    new rev::usb::SerialDriver()
Removed mention from file, it still is in source however that can be removed at a later time.

2024-08-30 04:57 UTC, garrettsummerfi3ld commented on src/main/native/cpp/Drivers/SocketCAN/SocketCANDevice.cpp
> +        m_name = "SPARK MAX";
I've changed it to be generic, but I don't think it really matters too much, marking this as resolved unless something else is missing.

2024-08-30 05:01 UTC, merged